### ISSUE TITLE
Avoiding "Error: Auto-increment functor in a recursive rule"

### ISSUE THREAD

**Issue by sifislag** [souffle-lang/souffle#940] opened 2019-04-03 12:49 UTC
Hello,

I need to associate tuples (e.g., [1, "foo"]) with a unique identifier, so I can pass them to a Souffle functor (i.e., external C++ code).

I tried to use "$" via code like this ("Context" is the desired tuple type):

```
.decl ctxToNum(?ctx:Context, ?strCtx:number)
ctxToNum(?ctx, $):-
  isContext(?ctx).
```

However I get the following compile error:
`Error: Auto-increment functor in a recursive rule`

Which is a correct statement, yet unavoidable: I want to use the functor in a core computation, so it will definitely be part of a recursive rule.

Is this Souffle being too conservative? Is it trying to protect me from infinite value creation, or is there really a technical reason why new ids (via "$") absolutely cannot be produced in the middle of a recursive computation? Is there perhaps another way to do what I need?

Thanks,
Sifis.

**Comment by b-scholz** [comment] 2019-04-03 23:57
This is related to issue #362 and #401. 

The problem is that the semi-naive evaluation requires a certain amount of determinism (or at least how we have implemented it). 

Can you rewrite your rule?

**Comment by b-scholz** [comment] 2019-04-04 09:15
You have already a number associated to a context. Why do you need a tight packing?

**Comment by sifislag** [comment] 2019-04-04 10:26
[1, "foo"] and [1, "bar"] could be two different contexts so that number cannot identify the tuple.

More specifically, the problem in our case is that context has a different definition per analysis configuration, usually it is either a string or a record of strings (1 or more). 

One solution could be to provide a contextToStr(ctx, ctxStr) relation for every analysis configuration which would concatenate all the string values of the record (can be extended to work for numeric values as well using to_string). If I understand it correctly, the result of ord() on the concatenated string will provide a unique identifier for each context.

However this would require writing additional rules for each analysis configuration, which is what I'm trying to avoid in order to keep the analysis components as clean as possible. If I could achieve that using "$" it would be ideal as it would only require one rule. Do you know of any other simple way to achieve the same result?

**Comment by b-scholz** [comment] 2019-04-04 12:10
I have disabled the type-checker for the arguments of the ord() functor. 
Please have a look and check whether it will work for you.

**Comment by b-scholz** [comment] 2019-04-06 01:42
Can we close this issue?

**Closed** 2019-04-06 18:56 UTC
Labels: enhancement

**Comment by sifislag** [comment] 2019-04-06 19:19
Thanks, that is perfect for what I needed,
