### ISSUE TITLE
Remove unecessary compilaton 

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#134] opened 2016-06-08 17:34 UTC
Hi,

The main attraction of Souffle is its compiler. While in the JDK use cases compilation times of several minutes were negligible to the overall analysis time not all use cases are like this. A particular use case I have in mind, benefits greatly from the compiled souffle however, its compilation time is unacceptable. Further certain queries remain fairly static over time (good!) yet a few are quite dynamic. It would be nice if souffle was able to separate these queries in separate compilation units so that only the queries that need to be regenerated are compiled and then can be linked to the other compilation units. Perhaps this requires some annotation on the part of the user in the souffle language.

**Comment by b-scholz** [comment] 2016-06-08 23:12
Currently we have three different modes to run Souffle:

1) RAM Interpreter (no specific option)

2) Compile to C++ and execute (option -g) 

3) RAM Interpreter & Compile for feedback directed compilation (--auto-schedule)

Perhaps we could extend mode 3 for your use case. One idea to implement this is that we have a time threshold. If the time threshold is exceeded, we start the compilation process and transfer the current interpreter state to the C++ program.

**Comment by psubotic** [comment] 2016-06-08 23:16
yes but also it would be nice to have some rules in separate compilation units. For example if you 90% of your rules static and 10% dynamic - you don't want them as one compilation unit even though they are in the same datalog program.

**Comment by b-scholz** [comment] 2016-06-08 23:30
One solution is to have modules that interact with each other and the programmer can decide whether a module is "compiled" or "interpreted". In your setup, this could make sense, i.e., the static modules would be compiled and the dynamic modules are interpreted. 

The question here is how to handle the state transfer between modules. Ideally, we implement a runtime environment for modules that is also fully functional in the "cloud". This reminds me of the discussions we had in the past about the component model as well.

**Comment by psubotic** [comment] 2016-06-08 23:34
yes this is exactly what im thinking of. At the very least even if they are both compiled they are compiled to different C++ code or libraries. So every time something changes it only requires linking. But as you said, some could also be interpreted. 

Regarding state transfer - if they are both compiled and need to be linked I dont see an issue (on a first think about it) but im not sure how it would work if some are compiled and some interpreted.

**Comment by b-scholz** [comment] 2016-06-08 23:40
The interpreter and the C++ compiler of Souffle work differently and cannot interact easily. Also if you compile two modules separately, we will need to encapsulate the access to relations (heavily templatized code with not many interfaces after the instantiation). Hence, we need a new interface for modules, and an own semantics how modules operate with each other. The problem is that the module concept is outside of the semantic model of Datalog. It is more related to a stream programming or message passing.

**Comment by b-scholz** [comment] 2018-02-09 11:58
Perhaps we close this issue; it might be better to talk about faster interpreter / JIT for RAM.

**Closed by b-scholz** 2018-02-09 11:58 UTC
Labels: question
