### ISSUE TITLE
Incorrect result with eqrel?

### ISSUE THREAD

**Issue by bertram-gil** [souffle-lang/souffle#2163] opened 2022-01-02 11:43 UTC
Hi guys, 
Consider the following program: 
```
.decl two_set(x : number, y : number) eqrel
.decl union_two_set(x : number, y : number)
.decl unique2(x : number)
.decl equivalent(a: number, b: number) eqrel
.decl out(a: number)
.decl A(a:number, b:number) 
.output A 

two_set(1, 2).
two_set(3, 1).
two_set(6, 10).
unique2(1).
equivalent(1, 2).
equivalent(1, 3).

union_two_set(x, y) :- two_set(x, x), two_set(y, y).
out(x) :- equivalent(x, 1).

A(j, j) :- union_two_set(j, g), unique2(a),  equivalent(a, h).
```
Running the above program with Souffle gives me the following values for `A`: 
```
1	1
2	2
3	3
6	6
10	10
```
If I add a new rule `A(a, a) :- out(a), !out(a).` to get the following program: 
```
.decl two_set(x : number, y : number) eqrel
.decl union_two_set(x : number, y : number)
.decl unique2(x : number)
.decl equivalent(a: number, b: number) eqrel
.decl out(a: number)
.decl A(a:number, b:number) 
.output A 

two_set(1, 2).
two_set(3, 1).
two_set(6, 10).
unique2(1).
equivalent(1, 2).
equivalent(1, 3).

union_two_set(x, y) :- two_set(x, x), two_set(y, y).
out(x) :- equivalent(x, 1).

A(j, j) :- union_two_set(j, g), unique2(a),  equivalent(a, h).
A(a, a) :- out(a), !out(a).
```
Running the above program returns an empty result for `A`. But the result should not change. 

Souffle version I am using: 235a3bcd3811087208a7785b1583c01158541616

**Comment by b-scholz** [comment] 2022-01-03 12:11
With the latest performance changes of `eqrel`, we destroyed the iterators. A smaller example is the following:
```
.decl E(a:number, b:number) eqrel
E(1,2).
E(1,3).
 
.decl A()
A() :-
     E(1,_).
 
.decl B()
B() :-
  E(_,1).
.output  A,B
```
Both nullaries should contain the empty tuple. However, only the nullary `B` contains the empty tuple but not the nullary `A`.

**Comment by b-scholz** [comment] 2022-01-03 12:11
Can you check whether the latest release has the same issue?

**Comment by b-scholz** [comment] 2022-01-03 12:21
The problem is the execution of two subsequent existence checks on an equivalence relation, i.e., 
```
QUERY
    IF ((ISEMPTY(+disconnected1) AND (NOT ISEMPTY(E))) AND (NUMBER(1),UNDEF) IN E)
     INSERT () INTO +disconnected1
   END QUERY
```

**Comment by b-scholz** [comment] 2022-01-03 12:27
This is only an issue in the interpreter - not in the compiler - right?

**Comment by b-scholz** [comment] 2022-01-03 12:31
After further analysis, it seems to be an interpreter issue that undefined values for equivalence relations cause problems and this needs to be fixed in the Generator.

**Closed** 2022-01-14 09:08 UTC
Labels: bug - identified
