### ISSUE TITLE
Compiling with profile enabled takes significantly more time

### ISSUE THREAD

**Issue by gkastrinis** [souffle-lang/souffle#740] opened 2018-10-03 12:04 UTC
It is not uncommon for souffle compilation to take a long time in our setting (Doop).
Usually it is around 10 minutes. But when we try to combine it with profiling it is significantly more. For example, it could take 50 minutes and still not terminate.

Is there something that can be done in regards to that?

Btw, this seems to not be the case in older versions of souffle.

**Comment by b-scholz** [comment] 2018-10-03 21:54
We need to investigate. Is this happening with all versions of DOOP?
Also there is the suggestion to break up the compilation into compilation junks.

**Comment by mmcgr** [comment] 2018-10-04 07:36
An example would be helpful. Does it happen with any of the standard Doop benchmarks?

**Comment by gkastrinis** [comment] 2018-10-04 08:57
1) I haven't tried to look back at different Doop commits. It happens with the current version at least. But as I am told, the issue was not there with previous builts of souffle.

2) Benchmarks don't play any role in this. This is for the compilation step of a given analysis.

**Comment by psubotic** [comment] 2018-10-04 09:01
I think by benchmarks, Martin means Doop analyses, i..e,  does this happen
for the available Doop analyses so that the problem can be replicated?

**Comment by anantoni** [comment] 2018-10-04 09:03
Hi guys, we can provide you with the datalog files that take too long to compile, but as George suggested it seems that this was caused by a change in Souffle rather than a change in our codebase. 

Let's say that a Datalog file that would take 20mins to compile with profiling enabled can now take more than an hour to compile. For instance this would happen with an analysis that has reflection enabled. But even smaller analyses take more time to compile it's just not that the difference is not that significant.

**Comment by mmcgr** [comment] 2018-10-05 05:59
I didn't mean to suggest Doop had any problem, I was just looking for an example input that caused the issue. I think I've found an example with the datalog produced from a context sensitive analysis of antlr.jar. With profiling compilation with g++ 7.3 uses 15.7GB and 13 minutes, without profiling it uses 6.7GB and 5.5 minutes. That's not as extreme as what you describe, but a larger program, or less memory in the machine, would match what you describe.

If memory is the problem, then an immediate workaround is to use clang. Compilation time is similar, but in this example memory use was only 4.9GB with clang 6.0.


The main changes in profiling recently is just more logging. It looks like the increased compilation time is due to each profile logging command taking an oddly large amount of compilation resources. I suspect I can rewrite those commands to be less demanding of the compiler. I see some other changes I can make that will also improve compilation time.

**Comment by gkastrinis** [comment] 2018-10-05 10:27
It's not that far fetched that we could have had an unoptimized rule or something similar. So Doop having a problem is not out of question in general. We just tried to note that no significant changes in Doop lead to this behavior with different versions of souffle.

A colleague of mine will post a generated file that has this behavior so you can check :)

Btw, memory is not an issue since we are using a server with 256GB. Something else is the bottleneck.

**Comment by gfour** [comment] 2018-10-05 11:00
Hello all,

Here are some numbers:

(a) For a simple analysis, turning on profiling seems to incur a 3.8x overhead (which is not extreme):
```
$ ./doop -i ~/doop-benchmarks/dacapo-2006/antlr.jar -a context-insensitive --Xforce-recompile --id antlr-1
...
analysis compilation time (sec): 161                                           
...
$ ./doop -i ~/doop-benchmarks/dacapo-2006/antlr.jar -a context-insensitive --Xforce-recompile --souffle-profile --id antlr-1-profile
...
Analysis compilation time (sec): 616
...
```

(b) Also, a heavier analysis (that contains extra logic) with profiling off, makes compilation slower (as expected):
```
$ ./doop -i ~/doop-benchmarks/dacapo-2006/antlr.jar -a context-insensitive --Xforce-recompile --reflection-classic --id antlr-2
...
Analysis compilation time (sec): 544
...
```

(c) However, if we turn on profiling for that heavy analysis above, compilation seems to take even more time than 3.8x, it took about an hour before I had to kill it.
```
$ ./doop -i ~/doop-benchmarks/dacapo-2006/antlr.jar -a context-insensitive --Xforce-recompile --reflection-classic --souffle-profile --id antlr-2-profile
```

This is the logic file that shows the long compilation time: [context-insensitive.dl.zip](https://github.com/souffle-lang/souffle/files/2450003/context-insensitive.dl.zip)

We are using Souffle version 1.4.0-103-gddad1990.

**Comment by mmcgr** [comment] 2018-10-06 01:39
#741 will make some improvement to compilation for both profiled and unprofiled versions. In the example I used before compilation and memory use were reduced by ~40%.

**Comment by mmcgr** [comment] 2018-10-08 00:50
I've added a little more to #741 . Using the analysis from gfour,
With #741:
```
No profiling
3393932 maxRSS,         2:13.32 real,   132.34 user,    0.97 sys
Profiling
10656164 maxRSS,        8:53.54 real,   530.25 user,    3.25 sys
```
Without #741:
```
No profiling
9472160 maxRSS,         5:35.09 real,   332.49 user,    2.58 sys
Profiling
26091000 maxRSS,        30:13.43 real,  1802.18 user,   11.19 sys
```

**Comment by b-scholz** [comment] 2018-10-08 10:36
Is this fixed now?

**Comment by anantoni** [comment] 2018-10-08 14:28
Yes, the "heavy" command posted by @gfour now takes ~700 seconds. Thanks guys!

**Closed** 2018-10-08 14:29 UTC
Labels: enhancement

**Comment by anantoni** [comment] 2018-10-13 11:04
Down to ~220 now with the latest changes from Martin!
