### ISSUE TITLE
User-defined functors with floats (continued)

### ISSUE THREAD

**Issue by mclements** [souffle-lang/souffle#1927] opened 2021-05-05 06:25 UTC
Thank you for the previous bug fix. In further investigating how to use math libraries in Souffle, I used the following Datalog test code:

```
.decl Summary(label:symbol,y:float)
.functor exp(float):float
Summary("exp(1.0)", @exp(1.0)) :- true.
.output Summary
```

and used one of the following calls to use libm directly:

```
souffle -c -lm minimal.dl && cat Summary.csv # ok
souffle -lm minimal.dl && cat Summary.csv # fails "cannot find user-defined operator `exp`"
```

Interestingly, if I create a shared library that uses the `exp` function, then this test code is also okay in the interpreter. Is it obvious why the interpreter does not cope with the libm library?

**Comment by mclements** [comment] 2021-05-05 20:13
Moreover, for the following test code using the `r-mathlib` library:

```
.decl Summary(label: symbol, y: float)
.functor qnorm5(float,float,float,number,number): float
Summary("qnorm5(0.025,0.0,1.0,0,0)", @qnorm5(0.025,0.0,1.0,0,0)) :- true.
.output Summary
```

if I run `souffle -lRmath rmath.dl` then I get the correct output `qnorm5(0.025,0.0,1.0,0,0)	1.9599639845400538`. However, if I run:

```
souffle `pkg-config --libs libRmath` rmath.dl # or, equivalently
souffle -lRmath -lm rmath.dl
```

then I get an error `Error: Only one argument allowed for option 'libraries`. Is there any reason to constrain Souffle to one library?

**Comment by b-scholz** [comment] 2021-05-05 23:32
It is great that you are testing all this. We have never attempted to link a standard library directly. 
Could you set the LD_LIBRARY_PATH pointing to the standard library? Also, there is the flag -L setting the library path.

**Comment by b-scholz** [comment] 2021-05-06 04:56
I tried it on a MAC OS X machine, and it works out of the box.

**Comment by mclements** [comment] 2021-05-06 07:10
For my first report above, I was unsuccessful with various combinations of `LD_LIBRARY_PATH=` and `--library-dir=`. Note that the same Datalog file is fine with `souffle -lRmath minimal.dl` - so I then looked more closely at libm. Under Ubuntu 20.04 LTS, `/usr/lib/x86_64-linux-gnu/libm.a` is an ld script:

```
/* GNU ld script
*/
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /usr/lib/x86_64-linux-gnu/libm-2.31.a /usr/lib/x86_64-linux-gnu/libmvec.a )
```

Will the interpreter cope with such a script?

**Comment by mclements** [comment] 2021-05-06 07:15
Another workaround is to use `souffle -lm-2.31 minimal.dl`.

**Comment by b-scholz** [comment] 2021-05-06 08:02
You can study the code here 

https://github.com/souffle-lang/souffle/blob/17bef0b5d97d2fad198770b8173f3155c05d89c5/src/interpreter/Engine.cpp#L214

that loads the library. 

The problem is a system problem (not a souffle problem) that `dlopen()` cannot find the shared library `libm.so`.

**Comment by mclements** [comment] 2021-05-06 11:53
Good call. Note that under my system, `libm.so` has a similar form to `libm.a`:

```
/* GNU ld script
*/
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /lib/x86_64-linux-gnu/libm.so.6  AS_NEEDED ( /lib/x86_64-linux-gnu/libmvec.so.1 ) )
```

One workaround could be to use `<gnu/lib-names.h>` to find the `LIBM_SO` macro variable - but this does not sound like a general solution. Given that we do not know about a general solution to using ld scripts in the interpreter _and_ we have multiple workarounds, then I suggest that we do nothing more at this time.

For my second inquiry: how difficult would it be to pass multiple libraries? Is this a parsing issue or a limitation of `Engine::loadDLL()`?

**Comment by b-scholz** [comment] 2021-05-06 13:11
You can pass multiple libraries; that is not a problem.

**Comment by mclements** [comment] 2021-05-06 20:25
I may be confused: from my second comment, I found that `souffle -lRmath -lm rmath.dl` fails.

For the record, I found a solution from GHC that uses regexs to parse the ld scripts: [see here](https://gitlab.haskell.org/ghc/ghc/blob/master/rts/Linker.c#L736). This does in code what I did by hand, where it finds the `GROUP` and then reads in the first file name. Again, we can come back to this.

**Comment by mclements** [comment] 2021-05-07 21:14
For completeness, I wrote a quick bash script to handle the ld scripts:

``` bash
#!/bin/bash

# Update lib for GNU ld scripts
# Assumes that the binary is the first indicated in whereis,
# with the ld script being of type "ASCII text", with the
# first file reference after "GROUP"

# depends on: whereis, sed, file, grep, basename

# BSD licence
# Mark Clements <mark.clements@ki.se> 2021-05-07

# remove the -l prefix and define libname
libname=$(echo $1 | sed 's/[-]l\(.*\)/lib\1.so/')
# extract the *first* library in whereis
fullname=$(whereis -b $libname | sed 's/[^ ]*[:] \([^ ]*\).*/\1/')
if [ -e $fullname ]
then
    if [ "$(file -b $fullname)"="ASCII text" ]
    then
	# extract the *first* filename after GROUP
	fullname2=$(grep '^GROUP' $fullname | \
			sed 's/^GROUP *[(] *\([^ \t()]*\)[.][aso]* *.*/\1/')
	if [ -n "$fullname2" ]
	then
	    # get basename and remove the lib prefix
	    shortname=$(basename $fullname2 | sed 's/^lib\(.*\)/\1/')
	    echo -l$shortname
	    exit
	fi
    fi
fi
# if fails somewhere then return the origin input
echo $1
```

Assuming this is named `lib_ldscript`, the script can be used by:

```
souffle `lib_ldscript -lm` minimal.dl
```

**Comment by b-scholz** [comment] 2021-05-07 22:41
That is wonderful - great work!

**Comment by b-scholz** [comment] 2021-05-07 22:41
Can we close the issue?

**Comment by mclements** [comment] 2021-05-08 07:01
What about the issue with `souffle -lRmath -lm rmath.dl` failing with `Error: Only one argument allowed for option 'libraries'`?

**Comment by b-scholz** [comment] 2021-05-08 07:19
Can you try `souffle -l 'Rmath m'? 

I.e., the libraries should be concatenated via blank.

**Comment by mclements** [comment] 2021-05-08 08:05
Nice! This solves the specific issue.

However, this is non-standard and breaks code that uses `pkg-config --libs` with multiple libraries. As a TODO, it would be nice to allow multiple `-l` values.

Did you want to close this issue or keep it open?

**Comment by b-scholz** [comment] 2021-05-08 08:17
Can you implement it? It should not be hard. The option handling is in `src/main.cpp`.

**Comment by mclements** [comment] 2021-05-09 14:08
See pull request #1929 - this very minor change seems to work. Again, it would be good to add some tests, although it may be difficult to make the tests portable.

**Closed** 2021-05-10 11:19 UTC
Labels: enhancement, question
