### ISSUE TITLE
About the CMakeList.txt

### ISSUE THREAD

**Issue by ytvivian98** [souffle-lang/souffle#1943] opened 2021-05-31 02:58 UTC
I'm so confused with the CMakeList.txt.

I try to use CMake to generate run files.
But I noticed that there are some wrong paths in the txt , such as `./src/swig/SwigInterface.h`(there's no package swig under the src) and  `./src/RamTransforms.cpp`(I can't even find this file)

**Comment by b-scholz** [comment] 2021-05-31 06:30
Are you referring to the new pull request or the current system in the master branch?

**Comment by ytvivian98** [comment] 2021-05-31 06:46
I just downloaded the souffle-master.zip and found the CMakeLists.txt under the package utilities

**Comment by b-scholz** [comment] 2021-05-31 06:48
We are going to switch to CMAKE soon. The current CMAKE support is very limited and I cannot recommend it. 
I would suggest trying the new PR called CMAKE if you are interested in this. 

Regards,
Bernhard.

**Comment by ytvivian98** [comment] 2021-05-31 06:54
Thank you for answering my question.

**Comment by ytvivian98** [comment] 2021-05-31 06:59
So will you write a new usage document for Souffle later？

**Comment by b-scholz** [comment] 2021-06-01 02:13
We will rewrite the documentation for the new  cmake system.

**Comment by b-scholz** [comment] 2021-06-02 01:49
The CMake branch is merged. You can use cmake and autoconf/automake to build souffle.

**Comment by ytvivian98** [comment] 2021-06-03 09:08
![image](https://user-images.githubusercontent.com/48816085/120618306-883c0600-c48d-11eb-843f-567567bf0dc8.png)

I try to use CMake 3.20 to generate an executable file for Visual Stdio 2019 on my windows 10. However, the above error occurred

![image](https://user-images.githubusercontent.com/48816085/120619047-35168300-c48e-11eb-9596-a5dc56a0f173.png)

**Comment by b-scholz** [comment] 2021-06-03 09:11
I have never built Souffle on a Windows operation system. 

The issue is the LIBFFI library. If you can install it on a Windows system, it should work. 

Perhaps you can have a look here:
https://github.com/pgregory/libffi-msvc

**Comment by ytvivian98** [comment] 2021-06-03 09:11
By the way , I found that maybe the CMakeList.txt under the package src need to add something.
![image](https://user-images.githubusercontent.com/48816085/120619573-ae15da80-c48e-11eb-98dd-5ae5585f70e8.png)

**Comment by b-scholz** [comment] 2021-06-03 09:13
Can you run the CMakeList.txt in the main directory (not the one in the src directory). There it should be found, ie.,
```
# flex and bison
# --------------------------------------------------
find_package(FLEX REQUIRED)
find_package(BISON "3.0.4" REQUIRED)
```

**Comment by b-scholz** [comment] 2021-07-24 09:43
Can we close this issue?

**Closed** 2021-08-02 00:47 UTC
Labels: question
