### ISSUE TITLE
Assertion failed when using souffle

### ISSUE THREAD

**Issue by qunqunqun** [souffle-lang/souffle#1916] opened 2021-04-27 12:37 UTC
I use "./../souffle-2.0.2/src/souffle -t explain -F./facts -D./output main.dl"
However, the error occurs
```
souffle: ./include/souffle/datastructure/BTree.h:921: std::vector<souffle::range<souffle::detail::btree<Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater>::iterator> >& souffle::detail::btree<Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater>::node::collectChunks(std::vector<souffle::range<souffle::detail::btree<Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater>::iterator> >&, souffle::detail::btree<Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater>::size_type, const souffle::detail::btree<Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater>::iterator&, const souffle::detail::btree<Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater>::iterator&) const [with Key = souffle::Tuple<long int, 10>; Comparator = souffle::index_utils::comparator<0, 1, 2, 3, 4, 5, 6, 7, 8, 9>; Allocator = std::allocator<souffle::Tuple<long int, 10> >; unsigned int blockSize = 256; SearchStrategy = souffle::detail::binary_search; bool isSet = true; WeakComparator = souffle::index_utils::comparator<0, 1, 2, 3, 4, 5, 6, 7>; Updater = souffle::InterpreterProvenanceUpdater<10>; souffle::detail::btree<Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater>::size_type = long unsigned int]: Assertion `num > 0' failed.
Aborted (core dumped)
```
When I ignore the Assertion
```
qun@qun-OptiPlex-7080:~/Desktop/Experiment/ddisasm/main$ ./../souffle-2.0.2/src/souffle -F./facts -D./output main.dl -jauto -MARCH_AMD64
Floating-point arithmetic exception signal in rule:
function_symbol(EA,Name) :- 
   symbol(EA,_,"FUNC",_,_,_,_,Name).
in file /home/qun/Desktop/Experiment/ddisasm/main/main.dl [481:1-482:38]
qun@qun-OptiPlex-7080:~/Desktop/Experiment/ddisasm/main$ ./../souffle-2.0.2/src/souffle -t explain -F./facts -D./output main.dl -jauto -MARCH_AMD64
Floating-point arithmetic exception signal in rule:
function_symbol(EA,Name,1,(@level_num_0+1)) :- 
   symbol(EA,_,"FUNC",_,_,_,_,Name,_,@level_num_0).
in file /home/qun/Desktop/Experiment/ddisasm/main/main.dl [481:1-482:38]
```
Hoping for your answer!

**Comment by b-scholz** [comment] 2021-04-28 01:02
Can you reduce your input program and your input so that the error remains?
I assume this is only happening when provenance is enabled - right?

**Comment by qunqunqun** [comment] 2021-04-28 02:21
```
$ ./../souffle-2.0.2/src/souffle -F./facts -D./output main.dl -jauto -MARCH_AMD64
Floating-point arithmetic exception signal in rule:
function_symbol(EA,Name) :- 
   symbol(EA,_,"FUNC",_,_,_,_,Name).
in file /home/qun/Desktop/Experiment/ddisasm/main/main.dl [481:1-482:38]
```
With no provenance, the situation still happended. It's interesting that when I use -o to get an executable file and run it, there is no error, when I use normal model of souffle, the error happens.
The origin dl with input,output debug file is uploaded.

[main.zip](https://github.com/souffle-lang/souffle/files/6388666/main.zip)

**Comment by b-scholz** [comment] 2021-04-28 02:59
Can you run it without -jauto and -MARCH_AMD64 to see whether it is still crashing? 
It seems that the interpreter is affected.

**Comment by qunqunqun** [comment] 2021-04-28 03:00
The error occurs 
```
home/qun/Desktop/Experiment/ddisasm/main/main.dl:79: error:     #error "Undefined architecture"

        #error "Undefined architecture"
1 error in preprocessor.
Error: Undefined relation arch.pointer_size in file bitmasks.dl at line 32
    arch.pointer_size(Pt_size),

132 errors generated, evaluation aborted
```

**Comment by b-scholz** [comment] 2021-04-28 03:02
Ok. You need the -MARC_AMD64 flag.

Bernhard.

**Comment by qunqunqun** [comment] 2021-04-28 03:18
Oh I use it without  "-jauto" and it can run correctly, thank you for your patience!
However, using provenance cost a lot of time cost "7m14.215s"

**Comment by b-scholz** [comment] 2021-04-28 03:20
Well, this means that we have a concurrency bug, and it needs to be investigated.

**Comment by qunqunqun** [comment] 2021-05-02 05:06
using provenance cost a lot of time cost "7m14.215s" , is there also some problems because the normal excution without "provenance" is under 10s

**Comment by b-scholz** [comment] 2021-05-04 00:38
I can confirm that the interpreter has a data race. We need to investigate the cause of the race.

**Comment by b-scholz** [comment] 2021-05-04 00:38
I tested it on an AMD Ryzen with 32 cores.

**Comment by b-scholz** [comment] 2021-05-04 00:55
I checked the compiler. The compiler is working. It indicates that we have a data race in the interpreter. 
I.e., 
```
./../souffle-2.0.2/src/souffle -F./facts -D./output main.dl -jauto -MARCH_AMD64 -c
```
should work. 

Note it takes some time to build the executable. It might be better to generate the executable first and run it several times if needed for benchmarking, i.e.,
```
./../souffle-2.0.2/src/souffle -F./facts -D./output main.dl -jauto -MARCH_AMD64 -o ddisasm
```
and you can execute the executable with `./ddisasm`

**Comment by qunqunqun** [comment] 2021-05-04 02:03
> using provenance cost a lot of time cost "7m14.215s" , is there also some problems because the normal excution without "provenance" is under 10s

I wonder if you could give me some advice about this situation, thank you.

**Comment by b-scholz** [comment] 2021-05-04 02:07
Provenance has overheads so that proof trees can be constructed. I am surprised about the gap. 

Please can you use the compiler (-o) and (-j auto) for running your experiment. I.e., 
```
./../souffle-2.0.2/src/souffle -F./facts -D./output main.dl -jauto -MARCH_AMD64 -o ddisasm
```
and
```
./../souffle-2.0.2/src/souffle -F./facts -D./output main.dl -jauto -MARCH_AMD64 -o ddisasm_prov -t explain
```

Measure the runtime of both executables.

**Comment by b-scholz** [comment] 2021-05-05 02:44
Let's close this issue; @qunqunqun - please can you raise a new issue related to performance.

**Closed by b-scholz** 2021-05-05 02:44 UTC
Labels: bug - identified
