### ISSUE TITLE
Profiler html file is too large

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#434] opened 2017-07-28 21:22 UTC
We're doing some profiling.  The profiler has been great, but it sometimes generates html pages that are too large.  E.g. the one I'm looking at now is over 4MB and brings my browser to a crawl.  Is there some way you could save the relevant data but not have such a large web page?

Thanks!

**Comment by DominicRomanowski** [comment] 2017-07-29 05:38
Hi sean, a lot of the data comes from the iteration data that shows up only when you graph a rule/relation. A quick solution would be to add a flag when to ignore all that data. Otherwise a more permanent solution, such as a small socket server would need to be worked on.

**Comment by seanmcl** [comment] 2017-07-29 14:35
Hi Dominic,

The only thing we currently do is look at which relations are generating a lot of tuples.  If there's some easy way to optimize for that case, that would solve this particular issue.  

Thanks!

**Comment by b-scholz** [comment] 2017-07-31 07:46
The size of a relation should not be a problem. For a non-recursive rule there should be only few data records in the log file.  

Most likely, the problem arises because recursive rules produce a lot of data.  I believe there are various ways to address this issue:

- Pre-compute summaries for recursive rules  so that the browser does not need to compute them on the fly. 

- Have a small server instance running  

Dominic - what do you reckon is the easier option.

**Comment by DominicRomanowski** [comment] 2017-07-31 09:16
Right now I'm unable to install souffle and test my solutions, as I'm running on OSX..

I'm not 100% sure what exactly is causing it to be slow, as 4mb doesn't seem excessively large. It could be the sorting of the tables, or the recursion graphs.

If the problem is with the graphs, the quickest solution is to just not save that data into the json output if a flag is passed into the profiler (-s for summary?).

If the problem is with the sorting of the tables, I'm not too sure how to deal with it, having an example to try out would be helpful. Is it possible to get the profiler output that you were having trouble with?

**Comment by seanmcl** [comment] 2017-08-04 02:25
Sure, I can get you an example offline.

**Comment by mmcgr** [comment] 2018-10-08 14:05
Closing as the profiler html has changed substantially in the year since.

**Closed by mmcgr** 2018-10-08 14:05 UTC
Labels: enhancement
