### ISSUE TITLE
Usefull test script feedback

### ISSUE THREAD

**Issue by HerbertJordan** [souffle-lang/souffle#60] opened 2016-04-10 22:17 UTC
It is very frustrating if, after setting up a test cases, the test case is failing with the message
```
/evaluation.at:82: exit code was 127, expected 0
```
and running all the steps manually does not produce any errors. There is no more detailed log, nor any information that helps you narrowing down what the actual issue is -- which might be as little as an additional newline at the end of an input file or the wrong order of lines in the file.

While not only being super annoying and time consuming, it makes creating test cases a painful task that someone would wish to avoid or circumvent as much as possible.

The test script has to be improved in terms of usability.

**Comment by icesparrow** [comment] 2016-04-10 22:32
Well, `autotest` might not be very user-friendly at times, normally one has to go into the generated test directory and have a look at the output, there are `.out` and `.err` files that capture the standard and error output respectively. But I agree that if there were a more descriptive message that would be useful.

Could you give an example of what you are looking for, i.e.,  test input, command + output of a failing test you would like to see? I can have a look into how to solve the issue.

**Comment by b-scholz** [comment] 2016-04-12 08:20
Way back Kostyantyn showed me how to use autotest. It might be a little bit clunky and legacy from the early days of UNIX. However, it worked for me so far. As Kostyantyn mentioned, we set up the testcases so that the standard output and the error output is recorded. You can also re-run the test with the ./run script. Have a look.

If we have software engineers joining us in near future, we should have another look into this issue. My question is whether there exists more sophisticated test frameworks than autotest. For the time being, I would put this issue on hold.

What do you reckon?

**Comment by psubotic** [comment] 2016-04-12 09:47
I agree, we have to start prioritising. If this behaviour is constantly failing for no reason - we might have an issue. If its a matter of clunky error messaging, we just have to live with it for the short term.

**Comment by HerbertJordan** [comment] 2016-04-12 15:35
I was checking all the outputs (which have been empty as expected) and the generated csv files (which seemed to be identical to the reference) and still got only the message posted above in the log. 

I also was running the test individually, in its directory, resulting in exactly the same behavior. I just could not figure out which command actually produced the error code 127 (which would be typical for some seg-fault), and then i gave up. I pushed it, and on the build server it seems to work.

A log, that simply prints step by step the commands that are executed by the test script so that it can be re-run, without some environment variables like $SOUFFLE would be very helpful to narrow down the problem.

I do not agree that this is some minor side issue that can be associated to a low priority since it is effecting the efficiency of implementing any other new feature.

**Comment by HerbertJordan** [comment] 2016-04-12 17:05
FWI: i just spend another hour in figuring out how to track town an issue a test case using the test infrastructure after adding a modification that took me 20 minutes. I ended up taking the interface.at and testsuite.at apart to figure out what is going on.

Once I figured out what is wrong, I could run all the instructions successfully manually, but the test case still reported to me that it failed. It seems like there is no "reset" happening. In the end I wiped out the entire work space, cloned again, copied in my modifications and then it finally worked.

**Comment by psubotic** [comment] 2016-04-12 19:24
Sorry didn't realise its a perm problem - thought it was just a freak one off thing. I guess we have to figure something out then. Kostyantyn can you replicate this problem? Any idea what is causing it?

**Comment by icesparrow** [comment] 2016-04-12 21:07
Frankly, I am no seeing any issues with `autotest` at the very moment or before that for that matter, `autotest` is a bit awkward I agree, still one is supposed to pinpoint an issue by looking at the diffs or the exit code. `autotest` is supposed run a command and compare the actual output to the expected, if something is going wrong then I suppose there is a bug in the `autotest` configuration somewhere.

Herbert, could you please send me the commands + the branch you are currently using so I can investigate the issue? If there are some problems with failing tests which you cannot solve outright do feel free to dump that on me. Just give me some instructions how to replicate the issue.

I agree that there are better and more capable test frameworks out there, in `autotest` everything is done pretty much manually. We can write new macros of course, but there are frameworks that already provide much automation by design. I have heard a few nice things about [dejagnu](http://www.gnu.org/software/dejagnu/) but I have not tried that myself yet. Here at CEA we use a small yet capable framework called `ptest` which can run tests concurrently, easily update the oracles etc. For instance,

```
ptest -show sometest
```
will run the tests, get the outputs and use them as oracles, and

```
ptest -update sometest
```

will take the current outputs and use them as new oracles. I am not suggesting we use `ptest` (I do not want to bring a new dependency like Ocaml), I just want to point out the functionality I would look for.

With all that said, I am not sure if changing the test framework at the very moment is the right move, this is not something that can be done in 15 minutes. As Bernhard stated earlier there are more pressing issues. I can provide some support for `autotetst` now and eventually adopt a new test engine when we are ready to make a move.

**Comment by b-scholz** [comment] 2016-04-13 01:42
autotest is a very basic system. It translates M4 macros to shell scripts, and the generated shell scripts run the testscripts. In some ways, it is really up to us what we want from the tool - it is freely programmable, and it is truly flexible. If we have problems it is most likely related to how we defined our test macros.

Perhaps Herbert's issue  is related by not calling "make clean" in the tests directory. Changes are not picked up if the old scripts are not deleted. Herbert can you try?  Herbert - could you talk to Kostyantyn directly if the issue is still persistent. 

Again, I would suggest to defer this discussion until we have more engineering support.

**Comment by b-scholz** [comment] 2016-04-22 08:43
Can we close this issue and defer it to a later point in time?

**Comment by icesparrow** [comment] 2016-04-23 11:54
I have no problem closing the issue, but I am probably the last person to ask. In any case I think we should defer the issues until the second release.

Herbert, are you still having issues with autotest?

**Comment by b-scholz** [comment] 2016-04-23 12:06
It might have been related to a bug which I fixed earlier this week. Distcheck works now consistently for latest Debian/Ubuntu and MAC OS X. 
Let's close it. Herbert can re-open it if he wishes so.

**Closed by b-scholz** 2016-04-23 12:06 UTC
