### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#1754] opened 2020-11-23 03:02 UTC
Travis CI doesn't seem to be viable now, after its recent acquisition and change in priorities, so some changes need to be made.

**Goals:**
Testing PRs:
- basic style checks, ideally linting
- basic compilation
- datalog parsing
- integration testing

Distribution:
- debs/rpms/pkg of HEAD to unstable repos
- debs/rpms/pkg of new tag to stable repos and github releases

NB compilation/execution is prone to platform-specific problems so we test with gcc/clang, and osx/Ubuntu, plus a fairly specific Windows test.

**Current approach:**
Travis CI:
- gcc and clang tests with Ubuntu Focal (split up to make best use of travis resources)
- gcc and clang tests with OSX (split up to better use travis, and to work around OSX OMP issues)
- style check
- build packages with each PR - test building in PR, and to update make unstable repos from master
- update github docs

Jenkins:
- more in depth tests with docker containers
- coverage (slow, as parallel tests occasionally overwrite coverage data)
- linter (currently broken, and of questionable utility when not broken)
- makes packages for releases to ubuntu/debian LTS and dev releases

**New approach:**
- short term: Push all work to Jenkins
- medium term: Push some testing to new CI (github actions?)
- long term: Shut down Jenkins server and use a more open system

**Comment by b-scholz** [comment] 2020-11-23 06:01
Yes - as discussed, we have a short-term solution, but we need a stable long-term solution. 

The problem is that we need funds for continuous testing using more open systems because our usage will deplete the free limits very quickly (e.g. 120min free build time etc.).  

Long-term we may need to set up a consortium that provides continuous funding towards the souffle project.

**Comment by taipan-snake** [comment] 2021-03-23 01:53
I came across these docs which might make it easier to migrate to Github Actions: https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

As far as I can tell, Github Actions is free for public projects, so if it works then this should be suitable for us

**Comment by b-scholz** [comment] 2021-03-23 03:08
That would be amazing to use GitHub actions. I haven't looked into the building environments. 
I understand that they are not free of use like Travis-CI used to be. 

I would suggest that we switch to CMAKE first and consider GitHub actions as a new platform as a next step. 
We need to look into the pricing for the building environments and somebody who would do the porting.

**Comment by b-scholz** [comment] 2021-05-04 00:45
This is an update on the current situation before I close this issue. 

The University of Sydney infrastructure has been shut down because of security concerns of ICT.
Hence, the jenkins server plang1.it.usyd.edu.au is defunct. We need to salvage scripts/configurations before we shut it down. 

We needed to switch to GIT Actions swiftly. The next big step is to phase out autoconf/automake and use CMAKE instead.
Bintray has stopped its service and we may want to re-instantiate packaging via packageIO.

**Closed** 2021-05-04 00:46 UTC
Labels: release

**Comment by TomasPuverle** [comment] 2021-05-04 04:49
😨
