### ISSUE TITLE
C-Preprocessor

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#66] opened 2016-04-13 12:25 UTC
At the moment we rely on cpp to convert Datalog input programs with macros to programs without macros. The conversion is done in main.cpp. The popen() function invokes the cpp and returns a FILE handle on the converted program.

Unfortunately, various systems use different cpp versions/implementations. As a consequence, the behaviour of the macro expansion is not consistent.

My suggestion is to replace cpp with boost's wave library. This library implements a C-Preprocessor and can be added to the Souffle source code. Souffle has a UPL license. Hence I feel that using BOOST with a BSD style license should work (i.e. in general, I believe we cannot add code that has a GPL style license).

**Comment by icesparrow** [comment] 2016-04-13 12:47
This is true, there are different implementations thus the behaviours may vary. However, there are also various C standards that in addition to the features of the language define the behaviours of the preprocessor stating what a preprocessor should or should not do. In `clang`/`gcc` a certain standard can be forced using `-std` flag. For instance, to use only features described by C99 one can use a command like that:

```
gcc -E -pedantic -std=c99 somefile.c -osimefile.i
```

I think this may aid a problem at least for a short term. I have heard many nice things about boost, but this is a big dependency as well. So if we want to move away from CPP then how about m4? It is already there + it is much more powerful than CPP. Alternatively, there is a clang preprocessor, its output should be more consistent.

**Comment by HerbertJordan** [comment] 2016-04-13 13:03
In our setup we are using `cmake` to setup our build infrastructure. We added a rule, such that for every *.dl file in a certain folder, a *.h file is generated, which is then compiled with the standard C++ compiler.

The thing is: cmake relies on the C/C++ preprocessor include pragmas to detect file dependencies. Thus, if, for instance, you have a common header like `ir.dl` that gives you the basic definitions of some input facts or a utility file `utils.dl` offering basic components and definitions, which will be included in all kind of `*.dl` specifications, cmake will figure out the dependencies. If then `ir.dl` or `utils.dl` is edited, it will rebuild all the dependent specifications -- which makes life easy for us.

If we switch to a different notation, this feature will be gone.

**Comment by b-scholz** [comment] 2016-04-13 23:03
My feeling is that if we use a specific C-preprocessor in Souffle, then we don't have unexplained behaviour on various platforms (clang vs gcc etc.), and we don't need to hunt for various CPP options to find a common baseline (which might not be found). 

Boost's Wave can be made compliant to the latest C99/C++ standards. Have a look:

http://www.boost.org/doc/libs/1_60_0/libs/wave/doc/wave_driver.html

What we could do is to build wave in a separate source directory and invoke "wave" as we do now with "cpp" using popen(). This would be just a code dump of boost's wave driver and a new makefile to build wave in our project (effort of approx. 1/2 day).  This would be my preferred option -- it would permit to use other C-Preprocessors as well, i.e., it becomes configurable which cpp is used via the SOUFFLECPP environment variable if boost is not installed.

Alternatively, we fully integrate the wave interfaces into our project using Boost's C++ interfaces. The disadvantages of this approach is that we have a concrete source dependency on Boost (as Kostyantyn mentioned before).

**Comment by b-scholz** [comment] 2016-04-13 23:05
I forgot to answer Kostyantyn's question about M4. I believe Logicblox set a standard using the C-Preprocessor. I would suggest to stick to this so that the community does not need to learn a new preprocessor language.

**Comment by icesparrow** [comment] 2016-04-14 20:02
Yes, I agree that using a different preprocessor might not make some of the existing users happy. It's a shame though as `m4` has some really cool features. Although I still think that if the preprocessor that Soufflé requires complies to some accepted standard, e.g.,  C89, C99, C11, then we can have consistent behaviours across different platforms and this can be achieved by adding the flags I have mentioned before. After all this is the whole point of standartisation. Of course if some non-standard pragmas are needed then using a wave plugin is a good option.

**Comment by b-scholz** [comment] 2016-04-16 11:21
I have a preliminary version of the wave integration done in my branch 

http://github.com/b-scholz/souffle:wave

I will continue working on it the next few days. 

I run several tests and the output of GCC's cpp, CLANG's cpp, and wave is quite different. I believe integrating wave as a stand-alone tool in the souffle project might avoid future problems with the c-preprocessor. In addition, the wave system can be easily adjusted for our needs later on.

Herbert - could you have a look whether wave would cause troubles with your setup. Try to compile it and set the SOUFFLECPP variable to wave's executable.

**Comment by yanniss** [comment] 2016-04-28 16:27
I'm getting 
  sh: ./wave: No such file or directory
when I run souffle with an input file. It's easily resolved by adding a symlink to the wave executable in the current directory, but it sounds like a bug.

**Comment by yanniss** [comment] 2016-04-28 17:20
I'm having more issues that seem related to the wave integration. Lexical and parsing errors on large files result in silent exits of the souffle executable. The error is reported just fine if I only remove *comments*! I prepared a minimal example to demonstrate. Remove a single character from the comment, and the lexical error gets reported. It's not the number of lines that matter, it's the size of the commented-out text.
[temp.txt](https://github.com/souffle-lang/souffle/files/241062/temp.txt)

**Comment by yanniss** [comment] 2016-04-29 10:27
This problem also goes away with plain cpp. So, it's a wave issue, just like #103

**Comment by b-scholz** [comment] 2016-04-30 03:59
Unfortunately I cannot reproduce the issue that the executable of wave cannot be found.  How did you build the latest version of souffle. Can you do:

- make distclean
- sh bootstrap
- ./configure

and see whether the problem still persists. The file "wave" should be built in the src directory. If it is not there, the make system should stop with a failure. 

Which Red Hat system are you using? I will try to build a virtual machine that replicates your environment.

**Comment by yanniss** [comment] 2016-04-30 09:05
I did all the above and the problem persists. The only difference is that I do "sudo make install" and the executables go into /usr/local/bin. The wave executable is there as well. I use Fedora 23.

**Comment by yanniss** [comment] 2016-04-30 09:40
To reiterate the above: the problem is not that wave is not created or found, it is that souffle at some point tries to run 
   sh "./wave"
i.e., it looks for a "wave" executable in "."

**Comment by icesparrow** [comment] 2016-04-30 09:45
I am not having this problem either, I am using Gentoo Linux. So I suppose the issue that wave executable is either not built or not found by souffle.

@yanniss, could you please post configure and build logs if possible, that could help us to identify the issue.

**Comment by icesparrow** [comment] 2016-04-30 09:49
Config log should be in the build directory (`config.log`) and by build log I mean the standard output streams redirected to some file.

**Comment by yanniss** [comment] 2016-04-30 09:55
I'm not sure I agree with the diagnosis. The wave executable is built just fine and installed just fine in /usr/local/bin when I "make install". I can symlink to it from the current dir and souffle then works (modulo the other wave bugs identified, re: long comments and line numbers). 

But in any case, here's the config log.
[config.log.txt](https://github.com/souffle-lang/souffle/files/243533/config.log.txt)

**Comment by b-scholz** [comment] 2016-04-30 10:11
I believe the problem is caused by the function `GetAbsPath()` in `main.cpp` that produces the absolute path of an executable.  The problem is that automake/autoconf has various locations for binaries, i.e.,
 - source directory 
 - build directory (for out-of-source builds)
 - installation directory (--prefix)
and cannot be hard-coded.

To overcome this problem, the path of wave's executable is deduced from the absolute path of the "souffle" executable. Here, the underlying assumption is that "wave" co-resides in the same directory as "souffle". 

```
inline std::string getAbsPath(char * argv0)
```
Interestingly, (based from your error message) no absolute path could be computed for your souffle executable - it is relative, i.e., `./wave`. It seems that function realpath() fails on your system. Please could you replace `GetAbsPath()` by the following code:
```
inline std::string getAbsPath(char * argv0)
{
    char path[PATH_MAX];
    if (realpath (argv0, path) != 0) {
        return dirname(path);
    } else perror(NULL);
    return ".";
}
```

It could be an access error for `realpath()`.

If `realpath()` fails, we will understand the reason better executing  `perror(NULL)`. Let us know what the output of stderr is (in case it is failing).

**Comment by icesparrow** [comment] 2016-04-30 10:19
The issue is that when souffle is in the path, then argv0 (fed to `realpath`) if just `"souffle"`, so realpath fails. We need a simple implementation of `which` to fix that. Bernhard, I can address this issue if you like.

**Comment by yanniss** [comment] 2016-04-30 10:31
@icesparrow: yes, this is precisely the problem. "realpath" is used as a substitute of "which", which it is not. E.g., even from the command line:
$ which souffle
/usr/local/bin/souffle
$ realpath souffle
/home/yannis/pointer-analysis/souffle/souffle
(which is a nonsense path--I don't have a "souffle" file or symlink in that dir).

**Comment by b-scholz** [comment] 2016-04-30 11:25
Kostyantyn - if you could fix this quickly that would be great!

**Closed** 2016-05-17 07:34 UTC
Labels: bug, enhancement
