### ISSUE TITLE
guide about how to write parallelizable datalog rules

### ISSUE THREAD

**Issue by csabahruska** [souffle-lang/souffle#1443] opened 2020-05-06 22:34 UTC
Hello,
Is there any documentation that tells how to design datalog rules that helps souffle compiler to synthesize parallel evaluator?
I wrote a control flow analysis in souffle datalog that has many rules, but unfortunately souffle did not manage to parallelize it enough. I'd like to refactor my code and make it more parallel and faster.
My CFA code: https://github.com/grin-compiler/ghc-grin/tree/d7aebb21fd78eda7f86a85868f79d36a071038de/lambda-grin/souffle-datalog

Thanks!

**Comment by b-scholz** [comment] 2020-05-07 01:05
Can we start with optimizing the sequential program first? Can you generate a profile for the sequential program first using the command line: 
```
souffle -c <myprog> -p <myprog>.prof
souffle-profile <myprog> -j 
``` 
that will generate a profile `profile_html/<nr>.html` etc. 

Can you post the HTML? Again, let's do the sequential version first to understand whether there is further optimization potential in the sequential version. After this, let's have a look into the parallelization.

**Comment by csabahruska** [comment] 2020-05-07 08:44
[profiler_html.zip](https://github.com/souffle-lang/souffle/files/4591813/profiler_html.zip)

**Comment by b-scholz** [comment] 2020-05-07 08:47
Can you make your input size a little bit larger - say your program should run approx. 5min? The input should be representative of the problem that you want to solve.

**Comment by csabahruska** [comment] 2020-05-07 08:55
This was a representative sample. The input data is a large (2MB) whole program AST.
https://raw.githubusercontent.com/grin-compiler/ghc-grin/master/sample/tsumupto.2.lambda

[cfa-source-and-sample-input.zip](https://github.com/souffle-lang/souffle/files/4591858/cfa-source-and-sample-input.zip)

**Comment by csabahruska** [comment] 2020-05-07 09:03
I can run the CFA on bigger inputs also. But even for this smallest and meaningful sample input it took 20 mins for souffle-profile to generate the html from the 233MB prof file.

**Comment by b-scholz** [comment] 2020-05-07 09:08
The problem is that the parallelization targets long-running rules. Your total runtime is:

Total runtime: 24.8s (24.7601 seconds)

with the longest-running relations: 

```
Called   7.79s
TypeVarPointsTo  3.56s 
Array  2.96s
PointsTo  2.48s
ExternalOrigin  1.19s 
NodeOrigin 1.03s 
```

I believe the best approach would be the further optimize the sequential performance of `Called`, `TypeVarPoints`, and `Array` using better schedules for their rules.

Another approach is to start parallelizing the execution of relations (which we don't have at the moment). That might be advantageous considering your runtime. 

What is your target runtime (i.e. how fast do you want to have it)?

**Comment by csabahruska** [comment] 2020-05-07 09:26
I'd like to use the CFA analysis in a Haskell compiler as a part of the standard compilation pipeline. So the target runtime is under 1-3 sec. The plan to achieve this, is to extend the CFA algorithm to work on partitions of the whole program and calculating a worse control flow approximation instead of running it on the whole program AST. With this method the AST partition size could be adjusted to fit the analysis run time under the given limit.
Is there a paper or documentation about how the souffle compiler and runtime spawns new threads?

**Comment by b-scholz** [comment] 2020-05-07 09:50
We have some old papers but that has changed. 
Instead of focusing on parallelization, I would focus on sequential performance first. 
Perhaps we talk via skype next week.  Send me an email at Bernhard.Scholz@sydney.edu.au to arrange a meeting.

**Comment by csabahruska** [comment] 2020-05-07 09:52
Ok, I'll send an email today.
Thanks!

**Comment by csabahruska** [comment] 2020-05-16 13:38
I optimized the join orders a little and removed some redundant relations and the single-threaded run-time dropped from ~15 sec to 3.8 sec.

**Comment by b-scholz** [comment] 2020-05-18 00:03
Great job! Can you further optmise the following rules:
```
PointsTo(p,val) :- ReachableCode(alt), Alt(_,alt,tag), AltParameter(alt,i,p), NodeOrigin(alt,node), Node(node,tag), NodeArgument(node,i,val).
PointsTo(alt_val,scrut_val) :- Case(case_result,scrut), Reachable(case_result), Alt(case_result,alt_val,tag), NodeOrigin(scrut,scrut_val), Node(scrut_val,tag).
PointsTo(param,arg) :- ExecCall(ns,r,pnode,missing), PNode(pnode,fun,arity,missing), ExecCallArgument(ns,r,pnode,call_arg_i,arg), CodeParameter(fun, _tmp_0,param), call_arg_i >= 0, call_arg_i < missing, _tmp_0 = ((call_arg_i+arity)-missing).
```
Also, can you run Souffle without `-j <nr>`? That might be less distracting for performance optimisations.

**Comment by csabahruska** [comment] 2020-05-18 00:26
I did run souffle without -j <nr> option using the following commands:
```
souffle -c main.dl -p lambda-cfa.prof
souffle-profile lambda-cfa.prof -j
```
I've checked the PointsTo rules and tried a couple of reordering and value restriction but it always worsen the runtime. I believe it would need a better model design.

**Comment by b-scholz** [comment] 2020-05-18 00:29
Great - the other 3 relations with ~1s runtime - have you tried to optimise them as well?

**Comment by csabahruska** [comment] 2020-05-19 00:18
Is [feedback-directed compilation](https://souffle-lang.github.io/execute#feedback-directed-compilation) still available?

**Comment by b-scholz** [comment] 2020-05-19 00:48
Unfortunately, the cost metrics for the schedules were insufficient. We would need a new project to do this properly this time. We have removed it for the time being.

**Comment by b-scholz** [comment] 2020-05-19 03:43
I have removed the documentation about auto-scheduling - it was outdated.

**Comment by b-scholz** [comment] 2020-05-19 23:40
Is there still potential for optimisation? If not - we can think about how to implement task parallelism in Souffle.

**Comment by csabahruska** [comment] 2020-05-20 14:04
It think 0m3.534s is the fastest that I could optimize without changing the model.
OK. Let's talk about how to add task parallelism.

**Comment by b-scholz** [comment] 2020-05-21 01:32
Can you measure the parallel performance vs sequential performance first?

**Comment by b-scholz** [comment] 2020-05-21 01:40
Can you run your program with a range of job numbers, i.e.,  -j <nr> for nr, 1 <= nr <= 8? 

With that experiment, we can determine the scalability. 
Note it must be the compiled version (-j <nr> -o <exe.nr>) since the parallelization strategy of the interpreter is different.

**Comment by csabahruska** [comment] 2020-05-21 10:00
```
runs: 10

parallel, jobs: 1..8
  brie: (1 arity relations)
    10 x -j1 0m54.264s
    10 x -j2 0m45.657s
    10 x -j3 0m45.763s
    10 x -j4 0m47.759s
    10 x -j5 1m6.377s
    10 x -j6 1m9.974s
    10 x -j7 1m15.074s
    10 x -j8 1m20.522s

  btree: (all relations)
    10 x -j1 0m39.973s
    10 x -j2 0m28.048s
    10 x -j3 0m27.502s
    10 x -j4 0m27.557s
    10 x -j5 0m50.407s
    10 x -j6 0m53.824s
    10 x -j7 0m58.662s
    10 x -j8 1m4.320s

sequential (without -j):
  brie: (1 arity relations)
    0m30.350s

  btree: (all relations)
    0m35.316s

```

**Comment by b-scholz** [comment] 2020-05-21 10:50
Ok - that makes it clear that the current parallelization strategies don't work so well...

**Comment by b-scholz** [comment] 2020-05-21 11:59
Can you do the following modifications in Souffle:
 * ) utility/ParallelUtil.h can you redefine the following defintions:
```
    #define SECTIONS_START _Pragma("omp parallel sections") {
    #define SECTIONS_END }

    #define SECTION_START _Pragma("omp section") {
    #define SECTION_END }
```
 *) Comment out in main.cpp the following transformer
```
            std::make_unique<RamConditionalTransformer>(
                    // job count of 0 means all cores are used.
                    []() -> bool { return std::stoi(Global::config().get("jobs")) != 1; },
                    std::make_unique<ParallelTransformer>()),
```
 *) rebuild Souffle. 

Do the same experiment as before with the modified Souffle (but compiler only).

**Comment by csabahruska** [comment] 2020-05-21 12:03
So far I benchmarked the compiled version of the analysis. What do you mean by compiler only?

**Comment by b-scholz** [comment] 2020-05-21 12:10
The interpreter behaves differently - we don't want to run the interpreter with these modifications.

**Comment by csabahruska** [comment] 2020-05-21 12:45
```
runs: 10

parallel, jobs: 1..8
  brie: (1 arity relations)
    10 x -j1 0m28.732s
    10 x -j2 0m18.372s
    10 x -j3 0m18.267s
    10 x -j4 0m19.424s
    10 x -j5 0m16.760s
    10 x -j6 0m16.769s
    10 x -j7 0m16.891s
    10 x -j8 0m16.876s

  btree: (all relations)
    10 x -j1 0m34.262s
    10 x -j2 0m21.690s
    10 x -j3 0m20.949s
    10 x -j4 0m22.322s
    10 x -j5 0m19.490s
    10 x -j6 0m19.613s
    10 x -j7 0m19.554s
    10 x -j8 0m19.580s

sequential (without -j):
  brie: (1 arity relations)
    0m28.740s

  btree: (all relations)
    0m34.118s
```

**Comment by b-scholz** [comment] 2020-05-21 12:50
Better - right?

**Comment by b-scholz** [comment] 2020-05-21 12:51
How close is it to your target?

**Comment by csabahruska** [comment] 2020-05-21 13:43
Looks good, should be good enough. But is it possible to improve it further?

**Comment by b-scholz** [comment] 2020-05-21 13:48
I feel so but this would require much more work; basically we would need to change the model and rules.

**Comment by b-scholz** [comment] 2020-05-21 13:51
Can we close the issue?

**Comment by csabahruska** [comment] 2020-05-21 13:52
Ok. Thanks for the help.

**Comment by b-scholz** [comment] 2020-05-21 14:12
Welcome!

**Closed by b-scholz** 2020-05-21 14:12 UTC
Labels: question

**Comment by b-scholz** [comment] 2020-05-21 23:37
I forgot to mention that you could further improve the task parallelism. If a relation has several heavy-weight rules, you could split up the relation, i.e., 

```
.decl A(...) 
A( ...) :- ...  // long executing rule
A(...) :- ...  // long executing rule
```

into 
```
.decl A1(...) 
A1( ...) :- ... 
.decl A2(...) 
A2(...) :- ...
.decl A(..._
A(..) :- A1(...) // copy rule
A(..) :- A2(...) // copy rule
```
