### ISSUE TITLE
make test reported 3 errors

### ISSUE THREAD

**Issue by freedafeng** [souffle-lang/souffle#1339] opened 2020-03-05 21:42 UTC
I set the RAM_DOMAIN_SIZE to be 64bit, then compile and run "make test" command. This is the error I got.

834: functors                                        FAILED (interface.at:102)
835: functors   -j8                                  FAILED (interface.at:102)
836: functors   -c -j8                               FAILED (interface.at:102)

Please send `tests/testsuite.log' and all information you think might help:

   To: <souffle-talk@googlegroups.com>
   Subject: [souffle 1.7.1-850-g5f99b0fc] testsuite: 834 835 836 failed

You may investigate any problem if you feel able to do so, in which
case the test suite provides a good starting point.  Its output may
be found below `tests/testsuite.dir'.

Makefile:700: recipe for target 'check-local' failed
make[3]: *** [check-local] Error 1
make[3]: Leaving directory '/home/jackson/workspace/souffle/tests'
Makefile:567: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/jackson/workspace/souffle/tests'
Makefile:419: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/jackson/workspace/souffle/tests'
Makefile:696: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by b-scholz** [comment] 2020-03-05 23:45
Which system are you on (macOS / linux / etc.)?

**Comment by freedafeng** [comment] 2020-03-07 00:01
Ubuntu 18.04

**Comment by b-scholz** [comment] 2020-03-09 04:23
We will investigate whether we can reproduce the issue.

**Comment by mmcgr** [comment] 2020-03-14 08:09
How do you set RAM_DOMAIN_SIZE? Easiest way is to configure with 
```
./configure --enable-64bit-domain
```

I don't really see how setting it elsewhere would be a problem, but it's all I can come up with. If that doesn't help, you can find more log output in `tests/testsuite.dir/834` (where 834 is the failed test number) after the test has run.

**Comment by b-scholz** [comment] 2020-03-16 09:49
Is it possible that you did not recompile souffle - i.e. try
```
make distclean
sh boostrap
./configure --enable-64bit-domain
make check 
```

**Comment by b-scholz** [comment] 2020-03-26 23:36
We could not reproduce this issue? Is it still prevalent?

**Comment by mmcgr** [comment] 2020-04-01 23:59
Closing this since it's been a month without feedback.

If you have any updates please reopen this issue. We would like to either fix the problem, or provide better feedback about the cause.

**Closed by mmcgr** 2020-04-01 23:59 UTC
Labels: bug
